    #!/bin/sh

    INSTDIR=/usr/local/cloudengines
    RETVAL=0

    start()
    {
        cd $INSTDIR
        chmod +w ./bin/hbplug.conf
        rm ./bin/hbplug.conf
        cp /etc/pogoplug.conf ./bin/hbplug.conf
        chmod -w ./bin/hbplug.conf

        echo -n "Starting hbplug:             "
        ulimit -n 65536
        ulimit -c unlimited
        nohup $INSTDIR/bin/hbwd $INSTDIR/bin/hbplug > /dev/null 2>&1 &
        echo "Success"

        return $RETVAL
    }

    stop() {
        echo -n "Shutting down hbplug:        "
        if pidof hbwd > /dev/null; then
            killall hbwd > /dev/null 2>&1
            retries=120
            while pidof hbwd > /dev/null && [ $retries -gt 0 ]; do
                sleep 1;
                let retries--
            done
            if [ $retries -eq 0 ]; then
                echo "Failure"
            else
                echo "Success"
            fi
        else
            echo "Not Running"
        fi

        return $RETVAL
    }

    restart() {
        stop
        start
    }

    #
    # Usage statement.
    #

    case "$1" in
        start)
            start
            ;;
        stop)
            stop
            ;;
        restart)
            restart
            ;;
        *)
            echo "usage: $0 {start|stop|restart}"
            exit 1
            ;;
    esac

